#!/bin/bash

cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug \
-Dlager_BUILD_TESTS=OFF -Dlager_BUILD_EXAMPLES=OFF -Dlager_BUILD_DOCS=OFF \
-Dzug_BUILD_TESTS=OFF -Dzug_BUILD_EXAMPLES=OFF -Dzug_BUILD_DOCS=OFF \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
